[DescriptEdit]
; Verhalten
AppendTimestamp=1
Editmodus=0
Language=auto

; Schrift
FontFace=Segoe UI
FontSize=11
TitleFontSize=12

; Farben (R,G,B)
HighlightColor=34,87,128
EditableBackgroundColor=236,236,236
ReadonlyBackgroundColor=255,255,255
